### PR TITLE
add react-icons for pause and play

### PR DESCRIPTION
**Pull request by en-chang**

### CODE REVIEW

**Comment by bkchu** [comment]
Couple of things:
1. Make sure the base branch you want to merge into is `develop`, not `master`.
2. Let's start to send a slack message containing the link to the PR in the `general` channel along with a minimal description. e.g.
> feature/31-react-icons: https://github.com/bkchu/dudoku/pull/11
3. Add a description to the PR preferably with a screenshot of the changes you made. (be specific in your PR what things you worked on)
4. Confirm your UI changes with Honjae.

In the image below, the last `Details` link is going the be the best deploy preview link. 
image

**Comment by bkchu** [comment]
There's a task on that ticket that mentions talking to honjae about which icon package would be recommended. I can ask Honjae to look through it.

**Comment by en-chang** [comment]
Cool I'll keep all those things and mind and I actually did check with him for the specific icons already.

**Review by bkchu — APPROVED** [review]
LGTM

**Pull request merged**
